[package]
name = "pixel-engine"
version = "0.1.0"
authors = ["Fernando Luiz Parisotto <fernando.parisotto@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.32.2"
gl = "0.13.0"
rand = "0.7.0"